CREATE TABLE IF NOT EXISTS user_auth (
  `USER_ID` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(255) NOT NULL,
  `USERNAME` VARCHAR(255) NOT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (USER_ID),
  UNIQUE KEY (EMAIL)
);
